name: Perfecto CI Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        working-directory: ./perfecto-ci-project
        run: mvn clean install

      - name: Run Tests
        working-directory: ./perfecto-ci-project
        run: |
          echo "Running tests with Perfecto..."
          mvn test -DPERFECTO_TOKEN=${{ secrets.PERFECTO_TOKEN }} -DPERFECTO_CLOUD=${{ secrets.PERFECTO_CLOUD }}
